version: '2'
services:
  application:
      image: ubuntu:16.04
      container_name: "terox.sf4.subscription-example.application"
      volumes:
          - .:/var/www/application

  nginx:
      image: nginx:1.11
      container_name: "terox.sf4.subscription-example.nginx"
      ports:
          - 8088:80

      links:
          - php

      volumes_from:
          - application

      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/application.conf:/etc/nginx/conf.d/default.conf

  php:
      build: docker/php7
      container_name: "terox.sf4.subscription-example.php"

      volumes_from:
          - application

      volumes:
        - ./docker/php7/application.pool.conf:/usr/local/etc/php-fpm.d/application.pool.conf
        - ./docker/php7/application.ini:/usr/local/etc/php/conf.d/application.ini

      links:
          - db
          # - rabbitmq

  db:
      image: mysql:5.7
      container_name: "terox.sf4.subscription-example.db"
      ports:
          - 3308:3306

      volumes:
        - ./docker/data/mysql/:/var/lib/mysql

      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE:      subscription_example
          MYSQL_USER:          db_user
          MYSQL_PASSWORD:      123456